### ISSUE TITLE
Are you still maintaining this?

### ISSUE THREAD

**Issue by ericmorand** [swimmadude66/loaderify#8]
Hi @swimmadude66,

I was wondering if you were still maintaining this project. I'm currently working on the same kind of BS transform and the name loaderify is so perfect. :)

If you don't want to maintain this project anymore, I'd very happy to grab it and make it evolve.

Let me know,

Eric.

**Comment by swimmadude66** [comment]
I am in fact maintaining it, just haven't had a ton of time to add to the features lately. If you'd like, I would be glad to add you as a contributor
